### ISSUE TITLE
New website theme

### ISSUE THREAD

**Issue by hathix** [CodingItForward/codingitforward.github.io#2]
Add bootstrap, multiple pages, new theming, etc. It's more complicated than it looks because we have to redo the whole page layout in Bootstrap. There's a branch on the website that uses a custom Bootstrap theme, which we could try to build off.

Could use templates from HTML5 Up: https://html5up.net/

- [Verti](https://html5up.net/verti)
- [Twenty](https://html5up.net/twenty)
- [Directive](https://html5up.net/directive)
- [Spectral](https://html5up.net/spectral)
- [Alpha](https://html5up.net/alpha)
- [Solid State](https://html5up.net/solid-state)
- [Stellar](https://html5up.net/stellar)

**Comment by aidan-fitz** [comment]
I like Alpha, Solid State, and Stellar. But it's hard to see how a theme would work on our site before we customize it. Maybe each person can plug a different theme, customize and test it?

**Comment by neilmartis** [comment]
@aidan-fitz That's a good idea

**Comment by neilmartis** [comment]
@hathix  @aidan-fitz I am using this as base to for the template design https://standards.usa.gov/
